### ISSUE TITLE
Networking coursework: TODO LIST

### ISSUE THREAD

**Issue by sofiia-tesliuk** [sofiia-tesliuk/cluster_mininet#1]
- [x] **Presentation**
- [x] **Documentation**
- [x] Architecture

- [x] **Topology**
    - [x] Two spine nodes
    - [x] Four leaf nodes
    - [x] Four TORs
    - [x] Four Hosts
- [ ] Use BGP, BFD, ECMP protocols
- [x] Run and pass ping all-to-all between hosts
- [x] Do random nodes shutdown/restore and prove that connectivity is not affected
